### ISSUE TITLE
(Un)serialization should be decoupled from the models itself

### ISSUE THREAD

**Issue by koenvo** [Torvaney/statsbombapi#2]
At the moment the information about (un)serialization of the json - provided by the `dataclasses_json` package - is tightly coupled to the definition of the models itself.

The (un)serialization should be moved to a separate module which allows easy:
1. swap the serialization engine (`dataclasses_json`) itself
2. change the serialization format

Furthermore the (un)serialization should be part of a Repository. And the Repository should be used by the APIClient. This makes it possible for the APIClient to perform caching of the results of the Repository.

This could lead to way better performance. 

Some first numbers:

| Library                  | Action  | Duration  |
| ----------------- | ------- | ---------: |
| LocalFileSystem  | read     | 50ms        |
| dataclasses_json | load     | 12304ms |
| pickle                    | dumps |       86ms |
| pickle                    | loads   |      159ms |

**Comment by Torvaney** [comment]
I'm going to close this, since I _think_ the required functionality is now supplied through the `loaders` and `decoders` setup.

Please let me know if I am mistaken!

**Comment by koenvo** [comment]
Those loaders look good. Sorry for not finishing this PR!

**Comment by Torvaney** [comment]
No apologies necessary!
